[package]
name = "time_decay_consensus"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
rust_decimal = "1.33"
rust_decimal_macros = "1"
clap = { version = "4.5", features = ["derive"] }
